      integer MAXPTS, MAX_MATCH, MAXGROUP, MAXPARAM, MAX_FREQ,
     1        MAX_DAMP, MAXPTS_RSP
      parameter (MAXPTS=62000, MAXPTS_RSP=620000, MAX_MATCH=400, MAXGROUP=10, MAXPARAM=15)
      parameter (MAX_FREQ=400, MAX_DAMP=1)
